export {default as TarjetadeMaquina} from './TarjetadeMaquina'
export {default as InputField} from './InputField'
export {default as TarjetaPedido} from './TarjetaPedido'
export {default as TarjetaCliente} from './TarjetaCliente'
export {default as TarjetaColaborador} from './TarjetaColaborador'
export {default as TarjetaPlista} from './TarjetaPlista'
export {default as TarjetaMlista} from './TarjetaMlista'
